# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20171113_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.PositiveIntegerField(choices=[(0, 'daily'), (1, 'weekly'), (2, 'monthly')], default=0),
        ),
    ]
